config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path(f"{settings.ADMIN_URL}django-rq/", include("django_rq.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("webapp.users.urls")),
    path("", include("webapp.base.urls")),
    path("new-job/", include("webapp.new_job.urls")),
]

if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

webapp/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("settings/", views.Settings.as_view(), name="settings"),
    path("history/", views.history, name="history"),
    path("result/<int:pk>/", views.result, name="result"),
    path(
        "download-csv/<int:pk>/", views.download_summed_csv, name="download_summed_csv"
    ),
    path(
        "download-csv-daily/<int:pk>/",
        views.download_summed_csv_daily,
        name="download_summed_csv_daily",
    ),
]

webapp/new_job/urls.py
from django.urls import path

from . import views

app_name = "new-job"

urlpatterns = [
    path("", views.new_job, name="start"),
    path("<int:pk>/upload-csvs/", views.upload_csvs, name="upload-csvs"),
    path("<int:pk>/select-meters/", views.select_meters, name="select-meters"),
    path("<int:pk>/finalise/", views.finalise, name="finalise"),
]

webapp/users/urls.py
from django.conf import settings
from django.urls import include
from django.urls import path

from . import views

if settings.USE_AUTH_SERVICE:
    urlpatterns = [
        path("", include("social_django.urls")),
        path("log-out/", views.logout, name="logout"),
        path("log-in/", views.Login.as_view(), name="login"),
        path("login-error/", views.LoginError.as_view(), name="login-error"),
    ]
else:
    urlpatterns = [
        path("", include("django.contrib.auth.urls")),
        path("register/", views.register, name="register"),
    ]

webapp/datasets/models.py
from django.db import models


class PostcodeGasElec2020(models.Model):
    postcode = models.CharField(max_length=9, primary_key=True)
    elec_mean = models.DecimalField(decimal_places=6, max_digits=12, null=True)
    gas_mean = models.DecimalField(decimal_places=6, max_digits=12, null=True)


class PostcodeGasElec2021(models.Model):
    postcode = models.CharField(max_length=9, primary_key=True)
    elec_mean = models.DecimalField(decimal_places=6, max_digits=12, null=True)
    gas_mean = models.DecimalField(decimal_places=6, max_digits=12, null=True)


class LSOAGasElec2021(models.Model):
    lsoa = models.CharField(max_length=9, primary_key=True)
    elec_mean = models.DecimalField(decimal_places=6, max_digits=12, null=True)
    gas_mean = models.DecimalField(decimal_places=6, max_digits=12, null=True)

webapp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    # First Name and Last Name do not cover name patterns around the globe.
    name = models.CharField("Name of User", blank=True, max_length=255)
    USER_TYPE_CHOICES = [
        ("Financial Analyst", "Financial Analyst"),
        ("Network Analyst", "Network Analyst"),
        ("Retrofit Evaluator", "Retrofit Evaluator"),
    ]
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, blank=True)

    powershaper_token = models.TextField("PowerShaper API token", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["id"]

webapp/base/forms.py
from django import forms

from webapp.base import services


class TokenForm(forms.Form):
    token = forms.CharField(
        label="PowerShaper API token",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    def clean(self):
        data = super().clean()

        response = services.get_meter_lists(token=data["token"])
        if response.status_code != 200:
            self.add_error(
                "token",
                forms.ValidationError(
                    "Error when contacting PowerShaper API -"
                    " please check token is correct."
                ),
            )

        return data

webapp/users/forms.py
from django.contrib.auth import forms
from django.core.exceptions import ValidationError

from webapp.users.models import User


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": "This username has already been taken."}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

webapp/base/views.py
import csv

import pandas as pd
from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.generic import FormView

from . import enums
from . import forms
from . import models
from .models import AnalysisJob
from .services import _date_range_to_datetime_range
from webapp.datasets.sets import lsoagaselec2021
from webapp.datasets.sets import postcodegaselec2021

# SAP10
GRAMS_CO_PER_KWH_ELECTRICITY = 136
GRAMS_CO_PER_KWH_GAS = 210


def home(request):
    return render(request, "base/home.html")


class Settings(LoginRequiredMixin, FormView):
    template_name = "base/settings.html"
    form_class = forms.TokenForm

    def get_initial(self):
        return {"token": self.request.user.powershaper_token}

    def get_context_data(self):
        context = super().get_context_data()
        context["valid_key"] = self.request.user.powershaper_token != ""
        return context

    def form_valid(self, form):
        self.request.user.powershaper_token = form.cleaned_data["token"]
        self.request.user.save()

        return self.render_to_response(self.get_context_data())


@login_required
def history(request):
    # TODO(anna): make sure we only fetch the columns we need
    data = AnalysisJob.objects.filter(user=request.user).exclude(submitted_at=None)
    p = Paginator(data, 20)
    page = request.GET.get("page")
    results = p.get_page(page)

    def _get_pct_saving(job, meter_type):
        try:
            result = job.jobresults_set.get(
                model_type=job.better_fit, meter_type=meter_type
            )
        except models.JobResults.DoesNotExist:
            return None

        return result.percent_savings

    context = {
        "jobs": [
            {
                "pk": job.pk,
                "ref": job.postcode,
                "status": job.status,
                "gas_saving": _get_pct_saving(job, enums.MeterType.GAS),
                "elec_saving": _get_pct_saving(job, enums.MeterType.ELEC),
                "submitted_at": job.submitted_at.date(),
            }
            for job in results
        ]
    }
    return render(request, "base/history.html", context)


def _date_to_dict(value):
    parts = value.split("-")
    return {"day": int(parts[2]), "month": int(parts[1]), "year": int(parts[0])}


def _output_for_if(
    job,
    model_type,
):
    try:
        elec_result = job.jobresults_set.get(
            model_type=model_type, meter_type=enums.MeterType.ELEC
        )
    except models.JobResults.DoesNotExist:
        return None
    try:
        gas_result = job.jobresults_set.get(
            model_type=model_type, meter_type=enums.MeterType.GAS
        )
    except models.JobResults.DoesNotExist:
        return None

    elec_daily_df = pd.DataFrame(elec_result.results)
    elec_daily_df["date"] = pd.to_datetime(elec_daily_df["date"], format="%Y-%m-%d")
    elec_daily_df = elec_daily_df.set_index(["date"])

    elec_reporting_period_at_least_365_days = (
        job.reporting_start_date + relativedelta(days=364) <= job.reporting_end_date
    )

    gas_daily_df = pd.DataFrame(gas_result.results)
    gas_daily_df["date"] = pd.to_datetime(gas_daily_df["date"], format="%Y-%m-%d")
    gas_daily_df = gas_daily_df.set_index(["date"])

    gas_reporting_period_at_least_365_days = (
        job.reporting_start_date + relativedelta(days=364) <= job.reporting_end_date
    )

    if (
        elec_reporting_period_at_least_365_days
        and gas_reporting_period_at_least_365_days
        and job.processing_finished_at
        and job.floor_area
    ):
        start_plus_364_days = job.reporting_start_date + relativedelta(days=364)

        elec_subset_df = elec_daily_df.loc[
            job.reporting_start_date : start_plus_364_days
        ]
        gas_subset_df = gas_daily_df.loc[job.reporting_start_date : start_plus_364_days]
        assert len(elec_subset_df) == 365
        assert len(gas_subset_df) == 365

        elec_counterfactual_usage_first_365_days = elec_subset_df.counterfactual.sum()
        elec_reporting_first_365_days_usage = elec_subset_df.observed.sum()
        gas_counterfactual_usage_first_365_days = gas_subset_df.counterfactual.sum()
        gas_reporting_first_365_days_usage = gas_subset_df.observed.sum()

        post_intervention = (
            elec_reporting_first_365_days_usage + gas_reporting_first_365_days_usage
        ) / job.floor_area
        pre_intervention = (
            elec_counterfactual_usage_first_365_days
            + gas_counterfactual_usage_first_365_days
        ) / job.floor_area
        co2_sum = (
            (
                elec_reporting_first_365_days_usage
                * (GRAMS_CO_PER_KWH_ELECTRICITY / 1000)
            )
            + (gas_reporting_first_365_days_usage * (GRAMS_CO_PER_KWH_GAS / 1000))
        ) / job.floor_area
    else:
        post_intervention = None
        pre_intervention = None
        co2_sum = None

    return {
        "post_intervention": post_intervention if post_intervention else None,
        "pre_intervention": pre_intervention if pre_intervention else None,
        "co2_sum": co2_sum if co2_sum else None,
    }


def _output_for(job, model_type, meter_type):
    try:
        result = job.jobresults_set.get(model_type=model_type, meter_type=meter_type)
    except models.JobResults.DoesNotExist:
        return None

    daily_df = pd.DataFrame(result.results)
    daily_df["date"] = pd.to_datetime(daily_df["date"], format="%Y-%m-%d")
    daily_df = daily_df.set_index(["date"])

    reporting_period_at_least_365_days = (
        job.reporting_start_date + relativedelta(days=364) <= job.reporting_end_date
    )
    if job.processing_finished_at:

        job_reporting_date_range = _date_range_to_datetime_range(
            job.reporting_start_date, job.reporting_end_date
        )

        report_subset_df = daily_df.loc[
            job_reporting_date_range.start.replace(
                tzinfo=None
            ) : job_reporting_date_range.end.replace(tzinfo=None)
        ]

        counterfactual_usage_total_reporting_period = (
            report_subset_df.counterfactual.sum()
        )
        reporting_first_total_reporting_period = report_subset_df.observed.sum()

        if meter_type == enums.MeterType.ELEC:
            co2_saving_kg = int(
                (
                    counterfactual_usage_total_reporting_period
                    - reporting_first_total_reporting_period
                )
                * (GRAMS_CO_PER_KWH_ELECTRICITY / 1000)
            )
        if meter_type == enums.MeterType.GAS:
            co2_saving_kg = int(
                (
                    counterfactual_usage_total_reporting_period
                    - reporting_first_total_reporting_period
                )
                * (GRAMS_CO_PER_KWH_GAS / 1000)
            )
    if reporting_period_at_least_365_days and job.processing_finished_at:
        start_plus_364_days = job.reporting_start_date + relativedelta(days=364)
        subset_df = daily_df.loc[job.reporting_start_date : start_plus_364_days]
        assert len(subset_df) == 365

        counterfactual_usage_first_365_days = subset_df.counterfactual.sum()
        reporting_first_365_days_usage = subset_df.observed.sum()
    else:
        counterfactual_usage_first_365_days = None
        reporting_first_365_days_usage = None

    return {
        "reduction": result.total_savings,
        "reduction_pct": result.percent_savings,
        "cvrmse": result.cvrmse,
        "nmbe": result.nmbe,
        "rsquared": result.rsquared,
        "reporting_kwh": reporting_first_365_days_usage,
        "co2_saving_kg": co2_saving_kg if counterfactual_usage_first_365_days else None,
        "daily_figures": [
            {
                "date": _date_to_dict(row["date"]),
                "observed": row["observed"],
                "counterfactual": row["counterfactual"],
                "savings": row["saving"],
            }
            for row in result.results
        ],
        "monthly_figures": [
            {
                "date": {"month": timestamp.month, "year": timestamp.year},
                "observed": values["observed"],
                "counterfactual": values["counterfactual"],
                "savings": values["saving"],
            }
            for timestamp, values in daily_df.resample("MS").sum().iterrows()
        ],
        "cumulative_figures": [
            {
                "date": {"month": timestamp.month, "year": timestamp.year},
                "observed": values["observed"],
                "counterfactual": values["counterfactual"],
                "savings": values["saving"],
            }
            for timestamp, values in daily_df.cumsum().iterrows()
        ],
    }


@login_required
def result(request, pk):
    job = get_object_or_404(AnalysisJob, user=request.user, pk=pk)

    try:
        postcode_average = postcodegaselec2021.get(job.postcode)
    except ValueError:
        postcode_average = None

    try:
        lsoa_average = lsoagaselec2021.get(job.lsoa)
    except ValueError:
        lsoa_average = None

    context = {
        "job": {
            "id": job.pk,
            "submitted_at": job.created_at,
            "started_at": job.processing_started_at,
            "finished_at": job.processing_finished_at,
            "reference": job.reference,
            "postcode": job.postcode,
            "baseline_period": (
                job.baseline_start_date,
                job.baseline_end_date,
            ),
            "intervention_period": (
                job.intervention_start_date,
                job.intervention_end_date,
            ),
            "reporting_period": (

webapp/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth import logout as django_logout
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from webapp.users import forms


def logout(request):
    django_logout(request)
    domain = settings.SOCIAL_AUTH_AUTH0_DOMAIN
    client_id = settings.SOCIAL_AUTH_AUTH0_KEY
    return_to = settings.SITE_URL
    return HttpResponseRedirect(
        f"https://{domain}/v2/logout?client_id={client_id}&returnTo={return_to}"
    )


class Login(RedirectView):
    url = settings.LOGIN_URL


class LoginError(TemplateView):
    template_name = "registration/login_error.html"


def register(request):
    form = forms.UserCreationForm()

    if request.method == "POST":
        form = forms.UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "An error occured during registration.")
    return render(request, "registration/register.html", {"form": form})

webapp/templates/base/about.html
{% extends 'main.html' %}

{% block title %}About{% endblock %}

{% block content %}
{% endblock content %}

webapp/templates/base/history.html
{% extends 'main.html' %}
{% load mathfilters %}
{% load static %}

{% block title %}History{% endblock %}

{% block content %}

    <div class="container mt-4 mb-5">
        <div class="row">
            <div class="col-lg-9 col">
                <h1>Result history</h1>

                {% if not jobs %}
                    <p>You've not run any analysis jobs yet so there are no results to show here. Do you want to <a href="{% url 'new-job:start' %}">start a new analysis job</a>?</p>
                {% else %}
                    <div class="card">
                        <table class="table table-striped mb-0">
                            <thead>
                                <th width="0">Job ID</th>
                                <th>Status</th>
                                <th>Ref</th>
                                <th>Gas</th>
                                <th>Elec</th>
                                <th>Created</th>
                            </thead>

                            <tbody>
                                {% for job in jobs %}
                                    <tr>
                                        <td class="text-end" width="0">
                                            <span class="text-muted">#{{ job.pk }}</span>
                                        </td>
                                        <td>{{ job.status }}</td>
                                        <td>{{ job.ref }}</td>
                                        <td>
                                            {% if job.gas_saving > 0 %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-caret-down-fill text-success" viewBox="0 0 16 16">
                                                    <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                                                </svg>
                                                -{{ job.gas_saving|floatformat:1 }}%
                                            {% elif job.gas_saving < 0 %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-caret-up-fill text-danger" viewBox="0 0 16 16">
                                                    <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                                                </svg>
                                                +{{ job.gas_saving|abs|floatformat:1 }}%
                                            {% else %}
                                                -
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if job.elec_saving > 0 %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-caret-down-fill text-success" viewBox="0 0 16 16">
                                                    <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                                                </svg>
                                                -{{ job.elec_saving|floatformat:1 }}%
                                            {% elif job.elec_saving < 0 %}
                                                <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-caret-up-fill text-danger" viewBox="0 0 16 16">
                                                    <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                                                </svg>
                                                +{{ job.elec_saving|abs|floatformat:1 }}%
                                            {% else %}
                                                -
                                            {% endif %}
                                        </td>
                                        <td>{{ job.submitted_at }}</td>
                                        {% if job.status == 'failed' %}
                                            <td>
                                                <a class="disabled">View</a>
                                            </td>
                                        {% else %}
                                            <td>
                                                <a href="{% url 'result' job.pk %}">View</a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    {% if results.has_previous or results.has_next %}
                        <nav>
                            <ul class="pagination justify-content-center">
                                {% if results.has_previous %}
                                    <li class="page-item"><a class="page-link"  href="?page={{results.previous_page_number}}">Previous</a></li>
                                {% else %}
                                    <li class="page-item disabled"><span class="page-link">Previous</span></li></li>
                                {% endif %}

                                {% if results.number|add:'-4' > 1 %}
                                    <li class="page-item"><a class="page-link"  href="?page={{ results.number|add:'-5' }}">&hellip;</a></li>
                                {% endif %}

                                {% for i in results.paginator.page_range %}
                                    {% if results.number == i %}
                                        <li class="page-item active" aria-current="page"><span class="page-link">{{i}}</span></li>
                                    {% elif i > results.number|add:'-5' and i < results.number|add:'5' %}
                                        <li class="page-item"><a class="page-link"  href="?page={{i}}">{{i}}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if results.paginator.num_pages > results.number|add:'4' %}
                                    <li class="page-item"><a class="page-link"  href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
                                {% endif %}

                                {% if results.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ results.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="page-item disabled"><span class="page-link">Next</span></li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/base/home.html
{% extends 'main.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}
{% block content %}
    <section class="s1" style="cursor: default; padding-bottom: 1rem;">
        <div class="banner">
            <img src="{% static 'imgs/home/Background_no_text.jpg' %}" class="d-block h-100 w-100" alt"PowerShaper Tracker">
            <h3 class="heading">Generate revenue-grade<br/>energy savings estimates for<br/>home retrofits with smart<br/>meter data only.</h3>
            <h3 class="heading2">Metered Energy Savings from <bold>CarbonCo-op</bold></h3>
            <br/>
        </div>
    </section>
    <section class="s1">
        <div class="about-wrapper main-container">
            <a class="btn" href="{% url 'new-job:start' %}">
                <h2>Click Here To Get Started</h2>
            </a>
        </div>
    </section>
{% endblock content %}

webapp/templates/base/settings.html
{% extends 'main.html' %}

{% block title %}Settings{% endblock %}
{% block content %}

    <div class="container mt-4 mb-5">
        <div class="row">
            <div class="col-lg-9 col">
                <h1>PowerShaper Monitor API key</h1>

                <p>If you are a PowerShaper Monitor user, PowerShaper Tracker can get data directly from PowerShaper Monitor.</p>

                <p>To do this you will need to find your API key <a href="https://app.powershaper.io/meters/settings/" target="_blank">on the PowerShaper Monitor settings page</a> (link opens in new window), paste it in the form below, and click "Save".</p>

                <form enctype="multipart/form-data" action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}

                    {% if valid_key %}
                        <p>✅ Great, we have a valid token. You can proceed to <a href="{% url 'new-job:start' %}">analyse data</a>.</p>
                    {% endif %}

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}